

from __future__ import annotations
from typing import Any
from pydantic import BaseModel, Field


class ComplexityInfo(BaseModel):
    time: str = Field(..., json_schema_extra={"example": "O(n log n)"})
    space: str = Field(..., json_schema_extra={"example": "O(n)"})


class ProblemSummary(BaseModel):
    slug:            str
    title:           str
    difficulty:      str
    acceptance_rate: float
    tags:            list[str]
    is_premium:      bool


class ProblemDetail(ProblemSummary):
    problem_statement: str
    constraints:       list[str]
    examples:          list[dict[str, Any]]
    complexity:        ComplexityInfo | None = None
    similar_problem_ids: list[str] = []


class SearchRequest(BaseModel):
    query:      str = Field(..., min_length=3,
                            json_schema_extra={"example": "two sum sliding window"})
    top_k:      int = Field(5, ge=1, le=20)
    difficulty: str | None = Field(
        None, json_schema_extra={"example": "Medium"})


class SearchResponse(BaseModel):
    results: list[ProblemSummary]
    query:   str


class SessionCreateRequest(BaseModel):
    slug:    str = Field(..., json_schema_extra={"example": "two-sum"})


class SessionResponse(BaseModel):
    session_id:    str
    slug:          str
    user_id:       str
    current_stage: int = Field(..., ge=0, le=6)
    max_stage:     int = 6


class HintRequest(BaseModel):
    session_id: str = Field(..., json_schema_extra={"example": "sess_xyz789"})


class HintResponse(BaseModel):
    slug:          str
    stage:         int = Field(..., ge=0, le=6)
    hint:          str
    is_final:      bool = Field(...,
                                description="True when stage == 6 (full solution)")
    next_stage:    int | None = None
    source:        str = Field(
        "db", description="'db' if from MongoDB, 'llm' if generated by Claude")


class ComplexityRequest(BaseModel):
    code:     str = Field(..., min_length=10,
                          json_schema_extra={"example": "def twoSum(nums, target):\n    ..."})
    language: str = Field("python", json_schema_extra={"example": "python"})


class ComplexityResponse(BaseModel):
    time_complexity:  str
    space_complexity: str
    explanation:      str
    language:         str


class RecommendRequest(BaseModel):
    slug:       str = Field(..., json_schema_extra={"example": "two-sum"})
    user_id:    str = Field(..., json_schema_extra={"example": "user_abc123"})
    top_k:      int = Field(5, ge=1, le=10)
    difficulty: str | None = Field(
        None, json_schema_extra={"example": "Medium"})


class RecommendResponse(BaseModel):
    based_on:    str
    recommended: list[ProblemSummary]
    reason:      str

class SessionCreateRequest(BaseModel):
    slug: str = Field(..., example="two-sum")